# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            'What?'
tagline:          'I have no idea what I'm doing'
description:      'We considered ourselves to be a powerful culture.'
url:              http://hyde.getpoole.com

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/poole/hyde
