# Dependencies
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            What
tagline:          'This place is not a place of honor'
description:      'We considered ourselves to be a powerful culture.'
url:              rdungeelv.github.io

author:
  name:           'Rita Dungee'
  url:            rdungeelv.github.io

paginate:         1
